fail_on_violations: true

haml:
  enabled: false
ruby:
  enabled: false
coffeescript:
  enabled: false
jshint:
  enabled: false
eslint:
  enabled: false
scss:
  enabled: false
haml:
  enabled: false
swift:
  enabled: false
