---
resources:
  - name: otp-develop
    type: git
    source:
      uri: https://github.com/mythic-tech/otp.git/
      branch: develop
  - name: otp-master
    type: git
    source:
      uri: https://github.com/mythic-tech/otp.git/
      branch: master

jobs:
  - name: test-develop
    public: true
    plan:
      - get: otp-develop
        trigger: true
      - task: otp-run-test-develop
        file: otp-develop/ci/otp-develop-test.yml
  - name: test-master
    public: true
    plan:
      - get: otp-master
        trigger: true
      - task: otp-run-test-master
        file: otp-master/ci/otp-master-test.yml
